# Generated by Django 4.0.3 on 2022-03-22 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchField',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fieldName', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('descr', models.CharField(max_length=400)),
                ('time_req', models.IntegerField()),
                ('tech_stack', models.JSONField(help_text='This includes the tech stack requirement for project', null=True)),
                ('sel_stud', models.JSONField(help_text='Roll number of the students selected for this project', null=True)),
                ('alloc_stat', models.BooleanField(default=False, help_text='This helps to determine if the project has been allocated to students')),
                ('req_stu_no', models.IntegerField(help_text='This helps in determining the number of students required for a project')),
                ('advisor_id', models.JSONField(help_text="This stores the advisor's name for this project", null=True)),
                ('apl_stud', models.JSONField(help_text='Roll number of the students who applied this project', null=True)),
                ('res_interest1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_res_interest1', to='prof.researchfield')),
                ('res_interest2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_res_interest2', to='prof.researchfield')),
                ('res_interest3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_res_interest3', to='prof.researchfield')),
            ],
        ),
        migrations.CreateModel(
            name='Prof',
            fields=[
                ('first_name', models.CharField(max_length=30)),
                ('sec_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=256, primary_key=True, serialize=False)),
                ('contact', models.CharField(max_length=13)),
                ('room_no', models.CharField(max_length=30)),
                ('website', models.CharField(max_length=500)),
                ('des', models.CharField(max_length=30)),
                ('lab_name', models.CharField(max_length=30)),
                ('stud_list', models.JSONField(help_text='This includes the list of students roll no which have worked under a particular prof', null=True)),
                ('res_interest1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prof_res_interest1', to='prof.researchfield')),
                ('res_interest2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prof_res_interest2', to='prof.researchfield')),
                ('res_interest3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prof_res_interest3', to='prof.researchfield')),
            ],
        ),
    ]
