# Generated by Django 4.0.3 on 2022-03-20 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prof',
            name='res_interest',
            field=models.JSONField(help_text='This includes the field in which the prof is interested', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='res_interest',
            field=models.JSONField(help_text='This includes the broad research field for a project', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='tech_stack',
            field=models.JSONField(help_text='This includes the tech stack requirement for project', null=True),
        ),
    ]
