# Generated by Django 4.0.3 on 2022-03-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0002_alter_project_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='apl_stud',
            field=models.JSONField(help_text='Roll number of the students who applied this project', null=True),
        ),
    ]
