# Generated by Django 4.0.3 on 2022-03-21 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0002_prof_res_interest_project_res_interest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prof',
            name='stud_list',
            field=models.JSONField(help_text='This includes the list of students roll no which have worked under a particular prof', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='advisor_id',
            field=models.JSONField(help_text="This stores the advisor id's for this project", null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='alloc_stat',
            field=models.BooleanField(default=False, help_text='This helps to determine if the project has been allocated to students'),
        ),
        migrations.AddField(
            model_name='project',
            name='req_stu_no',
            field=models.IntegerField(default=2, help_text='This helps in determining the number of students required for a project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='sel_stud',
            field=models.JSONField(help_text='Roll number of the students selected for this project', null=True),
        ),
        migrations.AlterField(
            model_name='prof',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
