# Generated by Django 4.0.3 on 2022-03-23 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0002_alter_prof_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='tech_stack',
            field=models.CharField(help_text='This includes the tech stack requirement for project', max_length=400, null=True),
        ),
    ]
