# Generated by Django 4.0.3 on 2022-03-22 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0003_prof_stud_list_project_advisor_id_project_alloc_stat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchField',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fieldName', models.CharField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='prof',
            name='res_interest',
        ),
        migrations.RemoveField(
            model_name='project',
            name='res_interest',
        ),
        migrations.AlterField(
            model_name='project',
            name='advisor_id',
            field=models.JSONField(help_text="This stores the advisor's name for this project", null=True),
        ),
        migrations.AddField(
            model_name='prof',
            name='res_interest1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prof_res_interest1', to='prof.researchfield'),
        ),
        migrations.AddField(
            model_name='prof',
            name='res_interest2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prof_res_interest2', to='prof.researchfield'),
        ),
        migrations.AddField(
            model_name='prof',
            name='res_interest3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prof_res_interest3', to='prof.researchfield'),
        ),
        migrations.AddField(
            model_name='project',
            name='res_interest1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_res_interest1', to='prof.researchfield'),
        ),
        migrations.AddField(
            model_name='project',
            name='res_interest2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_res_interest2', to='prof.researchfield'),
        ),
        migrations.AddField(
            model_name='project',
            name='res_interest3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_res_interest3', to='prof.researchfield'),
        ),
    ]
