# Generated by Django 4.0.3 on 2022-05-12 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0003_alter_project_tech_stack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='apl_stud',
            field=models.CharField(default='', help_text='Roll number of the students who applied this project', max_length=400),
        ),
    ]
