# Generated by Django 4.0.3 on 2022-03-22 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0005_prof_contact_prof_email_prof_room_no_prof_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prof',
            name='room_no',
            field=models.CharField(max_length=30),
        ),
    ]
