# Generated by Django 4.0.3 on 2022-05-13 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0006_prof_proj_list_alter_prof_stud_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='advisor_id',
            field=models.CharField(default='[]', help_text="This stores the advisor's name for this project", max_length=400),
        ),
    ]
