# Generated by Django 4.0.3 on 2022-05-13 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0008_alter_project_advisor_id_alter_project_apl_stud_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prof',
            name='proj_list',
        ),
        migrations.RemoveField(
            model_name='prof',
            name='stud_list',
        ),
    ]
