# Generated by Django 4.0.3 on 2022-05-13 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0009_remove_prof_proj_list_remove_prof_stud_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='advisor_id',
        ),
        migrations.RemoveField(
            model_name='project',
            name='apl_stud',
        ),
    ]
