# Generated by Django 4.0.3 on 2022-05-13 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0013_alter_project_advisor_id_alter_project_apl_stud'),
    ]

    operations = [
        migrations.AddField(
            model_name='prof',
            name='proj_list',
            field=models.CharField(default='[]', help_text='This includes the list of projects that the prof has listed', max_length=400),
        ),
        migrations.AddField(
            model_name='prof',
            name='stud_list',
            field=models.CharField(default='[]', help_text='This includes the list of students roll no which have worked under a particular prof', max_length=400),
        ),
    ]
