# Generated by Django 4.0.3 on 2022-05-13 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0014_prof_proj_list_prof_stud_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prof',
            name='proj_list',
            field=models.CharField(default='[]', help_text='This includes the list of projects that the prof has listed', max_length=400, null=True),
        ),
    ]
