# Generated by Django 4.0.3 on 2022-03-22 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prof', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('first_name', models.CharField(help_text='First Name', max_length=30)),
                ('sec_name', models.CharField(help_text='Second Name', max_length=30)),
                ('cgpa', models.FloatField(help_text="Student's CGPA")),
                ('roll_no', models.IntegerField(help_text="Student's Roll number", primary_key=True, serialize=False)),
                ('resume_link', models.CharField(help_text="This includes the student's resume link", max_length=200, null=True)),
                ('spec', models.CharField(choices=[('CSE', 'Computer Science Engineering'), ('ECE', 'Electronics and Communication Enginneering'), ('CSAI', 'Computer Science & Artificial Intelligence'), ('CSD', 'Computer Science & Design'), ('CSSS', 'Computer Science & Social Science'), ('CSB', 'Computer Science & Bio Science'), ('CSAM', 'Computer Science & Applied Mathematics')], default='CSE', help_text='Students specialization', max_length=4)),
                ('deg_type', models.CharField(choices=[('UG', 'Under Graduate Student'), ('PG', 'Under Graduate Student'), ('PhD', 'Post Doctorate Student')], default='UG', help_text='Student is a UG/PG or PhD student', max_length=4)),
                ('res_interest1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_res_interest1', to='prof.researchfield')),
                ('res_interest2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_res_interest2', to='prof.researchfield')),
                ('res_interest3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_res_interest3', to='prof.researchfield')),
            ],
        ),
    ]
