# Generated by Django 4.0.3 on 2022-03-20 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('sec_name', models.CharField(max_length=30)),
                ('cgpa', models.FloatField()),
                ('roll_no', models.IntegerField()),
            ],
        ),
    ]
