# Generated by Django 4.0.3 on 2022-03-20 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='res_interest',
            field=models.JSONField(help_text='This includes the field in which the student is interested', null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='cgpa',
            field=models.FloatField(help_text="Student's CGPA"),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.TextField(help_text='First Name', max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_no',
            field=models.IntegerField(help_text="Student's Roll number"),
        ),
        migrations.AlterField(
            model_name='student',
            name='sec_name',
            field=models.TextField(help_text='Second Name', max_length=30),
        ),
    ]
