# Generated by Django 4.0.3 on 2022-03-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='proj_applied',
            field=models.JSONField(help_text='List of projects in which the student has applied', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='proj_selected',
            field=models.JSONField(help_text='List of projects in which the student has been selected', null=True),
        ),
    ]
