# Generated by Django 4.0.3 on 2022-03-21 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_remove_student_id_alter_student_roll_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='deg_type',
            field=models.CharField(choices=[('UG', 'Under Graduate Student'), ('PG', 'Under Graduate Student'), ('PhD', 'Post Doctorate Student')], default='UG', help_text='Student is a UG/PG or PhD student', max_length=4),
        ),
        migrations.AddField(
            model_name='student',
            name='spec',
            field=models.CharField(choices=[('CSE', 'Computer Science Engineering'), ('ECE', 'Electronics and Communication Enginneering'), ('CSAI', 'Computer Science & Artificial Intelligence'), ('CSD', 'Computer Science & Design'), ('CSSS', 'Computer Science & Social Science'), ('CSB', 'Computer Science & Bio Science'), ('CSAM', 'Computer Science & Applied Mathematics')], default='CSE', help_text='Students specialization', max_length=4),
        ),
    ]
